# Generated by Django 6.0.5 on 2026-05-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_card', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('regular', 'Thường'), ('vip', 'VIP')], default='regular', max_length=20)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('status', models.CharField(choices=[('trong', 'Còn trống'), ('co_khach', 'Có khách'), ('bao_tri', 'Bảo trì')], default='trong', max_length=20)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=15)),
                ('capacity', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RoomType',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('quan_ly', 'Quản lý'), ('le_tan', 'Lễ tân / Nhân viên')], default='le_tan', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('hire_date', models.DateField()),
                ('shift', models.CharField(choices=[('sang', 'Ca sáng'), ('chieu', 'Ca chiều'), ('toi', 'Ca tối')], default='sang', max_length=20)),
                ('status', models.CharField(choices=[('dang_lam', 'Đang làm'), ('nghi_viec', 'Nghỉ việc')], default='dang_lam', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='hotel.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='hotel.user')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_o', 'Đang ở'), ('da_tra_phong', 'Đã trả phòng'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='hotel.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to='hotel.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='hotel.room')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_charge', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('service_charge', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('payment_status', models.CharField(choices=[('chua_thanh_toan', 'Chưa thanh toán'), ('da_thanh_toan', 'Đã thanh toán')], default='chua_thanh_toan', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản'), ('the', 'Thẻ')], max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='hotel.booking')),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='hotel.roomtype'),
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='hotel.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking_services', to='hotel.service')),
            ],
            options={
                'db_table': 'BookingService',
            },
        ),
    ]

