# Generated by Django 6.0.5 on 2026-05-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_sync_timestamp_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bookingservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'room_number']},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='Booking_custome_efe8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='Booking_room_id_0a457a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='Customer_phone_c02d81_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id_card'], name='Customer_id_card_6b88a9_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'status'], name='Employee_departm_29b275_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'status'], name='Room_room_ty_62b0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='User_usernam_1d735a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='User_email_ffa2e0_idx'),
        ),
    ]
